= Getting Started with this Workshop

:imagesdir: /images

== Getting Started with this Workshop

== Goals:
Connect to Develeopment IDE.
Install the CF CLI
Log into the Pivotal CLoud Foundry Application Manager.

Step 1:: Connecting to your developement environment:

For this Workshop we have provisioned an Eclipse dev environment. The environments are numbered 001 to 100
So if you are student 001 you will make use of workspace attendee-001.

----
http://workspace.cloudfoundry.awsworkshop.io//dashboard/#/ide/che/attendee-00<STUDENT NUMBER>
mkdir environment
----

Step 2:: Clone Lab repo:
----
cd ~/environment
git clone https://github.com/rniksch/AWS-PCF-Workshop.git
----

Step 3:: add the cf CLI repo:
----
sudo wget -O /etc/yum.repos.d/cloudfoundry-cli.repo https://packages.cloudfoundry.org/fedora/cloudfoundry-cli.repo
----

Step 4:: Install cf CLI:
----
sudo yum install cf-cli
----

Step 5:: Login to the PCF Foundation using the cf CLI:
----
cf login -a https://api.sys.pcf.cloudfoundry.awsworkshop.io -u Student<YOUR STUDENT NUMBER> --skip-ssl-validation
(Password = Passw0rd)
----

Each student has been given OrgManager access to the Org matching the student name.
You will note that when you login, the Org is already selected.

Orgs and Spaces are using in various ways. Customers we have engagded with use orgs as a means of project or team segration. Spaces are also used for either project or environment segragation.

e.g:
org = team, space = project
org = team1, space = frontend
org = team1, space = midtier

org = project, space = env
org = frontend, space = dev
org = frontend, space = prod

In this module you:
- installed the cf cli
- used the cf cli to connect to the Pivotal Cloud Foundry apps manager


